modLoader = "javafml"
loaderVersion = "[10,)"
issueTrackerURL = "https://github.com/downloadableduck/inventory-pets/issues"
license = "MIT"

[[mods]]
modId = "inventory_pets"
version = "${version}"
displayName = "Inventory Pets"
authors = "downloadableduck"
description = '''
Turn your inventory into a living, breathing world!
'''
logoFile = "assets/inventory_pets/icon.png"

[[dependencies.inventory_pets]]
modId = "neoforge"
type = "required"
versionRange = "[21.10,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.inventory_pets]]
modId = "minecraft"
type = "required"
versionRange = "[26.2,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "inventory_pets.mixins.json"
